/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/_app.withdraw'
import { Route as AppReceiveRouteImport } from './routes/_app.receive'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCountRouteImport } from './routes/_app.count'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCountRoute = AppCountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/count': typeof AppCountRoute
  '/home': typeof AppHomeRoute
  '/more': typeof AppMoreRoute
  '/receive': typeof AppReceiveRoute
  '/withdraw': typeof AppWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/count': typeof AppCountRoute
  '/home': typeof AppHomeRoute
  '/more': typeof AppMoreRoute
  '/receive': typeof AppReceiveRoute
  '/withdraw': typeof AppWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/count': typeof AppCountRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/receive': typeof AppReceiveRoute
  '/_app/withdraw': typeof AppWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/count'
    | '/home'
    | '/more'
    | '/receive'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/count' | '/home' | '/more' | '/receive' | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/count'
    | '/_app/home'
    | '/_app/more'
    | '/_app/receive'
    | '/_app/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive': {
      id: '/_app/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/count': {
      id: '/_app/count'
      path: '/count'
      fullPath: '/count'
      preLoaderRoute: typeof AppCountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCountRoute: typeof AppCountRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMoreRoute: typeof AppMoreRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCountRoute: AppCountRoute,
  AppHomeRoute: AppHomeRoute,
  AppMoreRoute: AppMoreRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
